/*2026-03-25 
*Laser_Iset.c
*Description:		*********====output 25Hz/40ms 50% square wave.====*******
*Laser Enable Iset:  Iout 0-100mA linearly by setting Pin VLIS 0-2.5V 
                    which is generated by PA4 DAC output.
*/

#include "stm32f10x.h"
#include "delay.h"
/**
  * @brief  initilize DAC1 with DMA2 and TIM2 to generate square wave for VLIS control
  * @param  VLIS VLIS_2V5 ,VLIS_1V25 ,VLIS_0V625 ,VLIS_0V3125 ,VLIS_0V15625
  * @retval 无
  */
	

//50% duty cycle square wave
uint16_t square_wave[2] = {194, 0};

void Dac_Dma2_Tim2_Init()
{
        /*开启时钟*/
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);    //开启GPIOA的时钟
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_DAC, ENABLE);    //开启DAC时钟
    RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA2, ENABLE);    //开启DMA时钟
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);    //开启定时器2时钟
  
        /*GPIO初始化*/
    GPIO_InitTypeDef GPIO_InitStructure;                    //定义结构体
  
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AIN;        //模拟输入模式
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_4;                //GPIO引脚A4
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_2MHz;        //GPIO速度50MHz    
    GPIO_Init(GPIOA, &GPIO_InitStructure);    

        /*定时器2配置*/
    TIM_PrescalerConfig(TIM2,48000-1,TIM_PSCReloadMode_Update);
    TIM_SetAutoreload(TIM2,2000-1);
    TIM_SelectOutputTrigger(TIM2,TIM_TRGOSource_Update);
  
        /*DAC_InitStruct 参数初始化*/
    DAC_InitTypeDef DAC_InitStruct;

    DAC_InitStruct.DAC_Trigger = DAC_Trigger_T2_TRGO;      //触发方式:定时器2触发
    DAC_InitStruct.DAC_WaveGeneration = DAC_WaveGeneration_None;  //不生成波形
    DAC_InitStruct.DAC_LFSRUnmask_TriangleAmplitude = DAC_LFSRUnmask_Bit0;
    DAC_InitStruct.DAC_OutputBuffer = DAC_OutputBuffer_Enable;   //输出缓冲使能
    DAC_Init(DAC_Channel_1,&DAC_InitStruct);  //
  

        /*DMA初始化*/
    DMA_InitTypeDef DMA_InitStructure;                                            //定义结构体变量
  

    DMA_InitStructure.DMA_PeripheralBaseAddr =  (uint32_t)&DAC -> DHR12R1;        //外设基地址
    DMA_InitStructure.DMA_PeripheralDataSize = DMA_PeripheralDataSize_HalfWord;    //外设数据宽度，选择半字
    DMA_InitStructure.DMA_PeripheralInc = DMA_PeripheralInc_Disable;            //外设地址自增，选择失能
  
    DMA_InitStructure.DMA_MemoryBaseAddr = (uint32_t)square_wave ;           //存储器基地址
    DMA_InitStructure.DMA_MemoryDataSize = DMA_MemoryDataSize_HalfWord;            //存储器数据宽度，选择半字，与源数据宽度对应
    DMA_InitStructure.DMA_MemoryInc = DMA_MemoryInc_Enable;                        //存储器地址自增，选择使能，每次转运后，数组移到下一个位置
  
    DMA_InitStructure.DMA_DIR = DMA_DIR_PeripheralDST;                            //数据传输方向，选择由存储到外设
    DMA_InitStructure.DMA_BufferSize = 2;                                        //转运的数据大小
    DMA_InitStructure.DMA_Mode = DMA_Mode_Circular;                                //模式，选择循环模式
    DMA_InitStructure.DMA_Priority = DMA_Priority_Medium;                        //优先级，选择中等
    DMA_InitStructure.DMA_M2M = DMA_M2M_Disable;                                    //非内存到内存
    DMA_Init(DMA2_Channel3, &DMA_InitStructure);                                //将结构体变量交给DMA_Init，配置DMA2的通道3
	
  
        /*使能*/
    TIM_Cmd(TIM2, ENABLE);                    //定时器2使能
    DMA_Cmd(DMA2_Channel3,ENABLE);  //使能dma
    DAC_Cmd(DAC_Channel_1, ENABLE); //使能DAC通道1
    DAC_DMACmd(DAC_Channel_1, ENABLE);  //使能DAC通道的DMA

}


/**
  * @brief  Convert DAC value to Voltage String (Format: X.XXV)
  */
static void ConvertToVolStr(uint16_t dacVal, char *buf)
{
    uint16_t vol = (uint16_t)((uint32_t)dacVal * 3300 / 4095);
    buf[0] = (vol / 1000) + '0';
    buf[1] = '.';
    buf[2] = ((vol / 100) % 10) + '0';
    buf[3] = ((vol / 10) % 10) + '0';
    buf[4] = 'V';
    buf[5] = '\0';
}

/**
  * @brief  Capture actual voltage using 20ms delay (for 25Hz wave)
  * @param  hStr: Buffer for High level string
  * @param  lStr: Buffer for Low level string
  */
void GetActualVoltageStr(char *hStr, char *lStr)
{
    uint16_t val1, val2;
    uint16_t maxV, minV;

    /* Capture 1st point */
    val1 = DAC_GetDataOutputValue(DAC_Channel_1);
    
    /* Delay 20ms (Half cycle of 25Hz) */
    Delay_ms(20); 
    
    /* Capture 2nd point */
    val2 = DAC_GetDataOutputValue(DAC_Channel_1);

    /* Identify Max and Min */
    maxV = (val1 > val2) ? val1 : val2;
    minV = (val1 > val2) ? val2 : val1;

    /* Format strings */
    ConvertToVolStr(maxV, hStr);
    ConvertToVolStr(minV, lStr);
}
/**
 * @brief 随时更改电压幅值（可以在 while 循环里调用）
 * @param v_high: 高电平对应的 DAC 值 (0-4095)
 */
void Set_Dac_Amplitude(uint16_t v_high)
{
    // 直接修改内存里的值，DMA 会在下一次搬运时自动带走新值
    square_wave[0] = v_high;
    square_wave[1] = 0; // 低电平保持 0
}


/**
 * @brief  初始化激光器使能引脚 PB6
 * @note   逻辑：在配置为输出前先强制拉低，防止 ATLS 内部上拉导致误触发
 */
void Laser_EN_Init(void) {
    GPIO_InitTypeDef GPIO_InitStructure;

    /* 1. 开启 GPIOB 时钟 */
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB, ENABLE);

    /* 2. 关键：在配置模式前，先向位清除寄存器写入 1，强行将电平拉低 */
    /* 这样做是为了抵消 ATLS 内部上拉电阻在引脚切换到输出模式瞬间的影响 */
    GPIO_ResetBits(GPIOB, GPIO_Pin_6);

    /* 3. 配置引脚参数 */
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_6;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;    // 推挽输出
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_2MHz;    // 使能端不涉及高速切换，2MHz 纹波更小
    
    GPIO_Init(GPIOB, &GPIO_InitStructure);
    
    /* 4. 再次确认初始状态为关闭（低电平） */
    GPIO_ResetBits(GPIOB, GPIO_Pin_6);
}

/**
 * @brief  开启激光器总电源（使能）
 */
void Laser_Enable(void) {
    GPIO_SetBits(GPIOB, GPIO_Pin_6);
}

/**
 * @brief  关闭激光器总电源（紧急关断）
 */
void Laser_Disable(void) {
    GPIO_ResetBits(GPIOB, GPIO_Pin_6);
}
